workflows:
  react-native-ios:
    name: React Native iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: "Brisbane Wharf Box API"

    environment:
      groups:
        - Box

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.briscsba.neharfosde

      vars:
        BUNDLE_ID: "com.briscsba.neharfosde"
        XCODE_WORKSPACE: "ios/BrisbaneWharfBox.xcworkspace"
        XCODE_SCHEME: "BrisbaneWharfBox"
        APP_STORE_APPLE_ID: 6748035304

      node: 18.18.0
      xcode: latest

    scripts:
      - name: Clean cache and pods
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ios/Pods
          cd ios
          pod deintegrate
          pod install
          cd ..

      - name: Install dependencies
        script: |
          npm install

      - name: Set up provisioning profiles
        script: xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      email:
        recipients:
          - olya0665643972@gmail.com
        notify:
          success: true
          failure: true

      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
